### PR TITLE
add "Extension + Server" configuration to launch.json

### PR DESCRIPTION
**Pull request by wataash**
It's handy and many projects have it.

- https://github.com/Microsoft/vscode-mock-debug/blob/master/.vscode/launch.json#L49
- https://github.com/Microsoft/vscode-node-debug/blob/master/.vscode/launch.json#L61
- https://github.com/DonJayamanne/pythonVSCode/blob/master/.vscode/launch.json#L73

### CODE REVIEW

**Comment by rogalmic** [comment]
I added push rights for you, since currently i have very limited time for non-commercial work. Have fun :)

**Comment by wataash** [comment]
Thanks! :smile:

**Comment by wataash** [comment]
But I can't push commits to master:

```
$ git push upstream feature/RunExServerConf:master
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.01 KiB | 0 bytes/s, done.
Total 8 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To github.com:rogalmic/vscode-bash-debug.git
 ! [remote rejected] feature/RunExServerConf -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:rogalmic/vscode-bash-debug.git'
```

nor merge them on github:

image


Could you uncheck "Require pull request reviews before merging" in the protection settings for master branch?

image

**Comment by rogalmic** [comment]
Done...

**Pull request merged**
