### PR TITLE
ci: use proper node verisons

### PR DESCRIPTION
**Pull request by wataash**
Please see the commit message.

### CODE REVIEW

**Comment by rogalmic** [comment]
Looks  ok! 

I think  you can use "chore: some info" while creating squash and merge commit, then it will not show in changelog...

**Comment by wataash** [comment]
> Actually "ci: some message is fine as well"

Sorry, what do you mean?

**Comment by rogalmic** [comment]
After writing the answer i noticed that you already started using the commit naming scheme:
"ci: use proper node verisons"

That "ci: " type seems to be ok for this kind of change. 

Sorry for the misunderstanding, I need to read stuff twice before clicking send :).

**Comment by wataash** [comment]
:+1:

**Pull request merged**
