### PR TITLE
feat: add new property argsString

### LINKED ISSUE #138: Accept additional parameter `commandline` for arguments in string
VS Code does not support passing arguments to `args` in a string instead of an array of string. See https://github.com/microsoft/vscode/issues/83678.

However, due to that, is impossible for users to use "prompt for arguments" when launching a debug session. 

VS Code team suggest the extension owners to provide an additional parameter for debbuging configuration. See https://github.com/microsoft/vscode/issues/83678#issuecomment-592600592

It would look like then:
```JSON
{
  "version": "0.2.0",
  "configurations": [
      {
        "type": "bashdb",
        "request": "launch",
        "name": "Bash-Debug (simplest configuration)",
        "program": "${file}",
        "cwd": "${workspaceFolder}",
        "commandline": "-foo -bar /hello/world -o -p"
      }
    ]
}
```
And then, we would be able to do something like:
```JSON
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bashdb",
      "request": "launch",
      "name": "Bash-Debug (simplest configuration)",
      "program": "${file}",
      "cwd": "${workspaceFolder}",
      "commandline": "${input:arguments}"
    }
  ],
  "inputs": [
    {
      "id": "arguments",
      "type": "promptString",
      "default": "--help",
      "description": "The arguments to pass to the script"
    }
  ]
}

```

### PR DESCRIPTION
**Pull request by felipecassiors**
Fixes #138

### CODE REVIEW

**Comment by felipecassiors** [comment]
I'm testing this way:
l0p7925PsW

**Comment by rogalmic** [comment]
Hmm, I like this, since it takes parsing away from extension :)

Did you test the case where `argsString` is not set in `launch.json`?

**Comment by felipecassiors** [comment]
I forgot to say, it is WIP. I should at least test it more extensively.

**Comment by felipecassiors** [comment]
I'm using this to test: 
https://github.com/felipecassiors/vscode-bash-debug-test

**Comment by felipecassiors** [comment]
> Hmm, I like this, since it takes parsing away from extension :)
> 
> Did you test the case where `argsString` is not set in `launch.json`?

Tested, and now it works. However, the solution is a bit clunky.

JyA71SQXCu
https://github.com/felipecassiors/vscode-bash-debug-test

**Comment by felipecassiors** [comment]
@rogalmic what do you think now?

**Comment by rogalmic** [comment]
I would prefer to additionally handle empty `argString` in extension.ts -> resolveDebugConfiguration(), just to keep handling consistent. The changes in other files are fine.


See how args are handled:
```
		// Fill non-"required" attributes with default values to prevent bashdb (or other programs) from panic
		if (!config.args) {
			config.args = [];
		}
		else if (!Array.isArray(config.args)) {
			return vscode.window.showErrorMessage("Please specify `args` as array of strings in launch.json.").then(_ => { return undefined; });
		}
```

**Comment by felipecassiors** [comment]
Fixed due to your comment, way better indeed. 

I also used a new approach for your argument parsing. `shell-quote` already provides a method for transforming args array into a string, so why not use it instead? And also, I perform no parsing anymore at argsString. The value should be already properly escaped under JSON, and in case we use the input, it will also write the values accordingly in the JSON. This enabled a much cleaner usage, take a look at how do I pass environment variables and even expansive commands. 

oiYD8n6lBN

**Comment by felipecassiors** [comment]
I think this is now ready for your testing/merging. I suggest merging this PR using squash.

**Comment by rogalmic** [comment]
OK, looks very good. I will merge this to master, then test a bit. Afterwards it will be released.

It will be available for manual install* under `downloads@latest` link in:
https://marketplace.visualstudio.com/items?itemName=rogalmic.bash-debug

* This will have same version as current release, so manual uninstall + vscode restart is needed.

**Comment by felipecassiors** [comment]
Awesome, I'm already using it! 👍

**Pull request merged**
